workflows:
  xamarin-workflow:
    name: Build Xamarin App
    max_build_duration: 60
    environment:
      docker: 
        image: mono:latest  # صورة Docker تحتوي على Mono مثبتًا
    scripts:
      - name: Restore dependencies
        script: |
          nuget restore MyApp.sln
      - name: Build Android App
        script: |
          msbuild MyApp.Android/MyApp.Android.csproj /t:Clean /t:Build /p:Configuration=Release
      - name: Build iOS App
        script: |
          msbuild MyApp.iOS/MyApp.iOS.csproj /t:Clean /t:Build /p:Configuration=Release
    artifacts:
      - MyApp.Android/bin/Release/*.apk
      - MyApp.iOS/bin/iPhone/Release/*.ipa
